---
- hosts: playground
 #become: yes
 #become_method: sudo
  remote_user: cloud_user
  gather_facts: yes
  tasks:
    - name: install git
      yum:
        name: git
        state: latest
    - name: create repo directory
      file:
        path: /home/cloud_user/playbooks
        owner: cloud_user
        group: cloud_user
        mode: 0777
        state: directory
    - name: clone repo
      git:
        repo: https://github.com/RP91/playbooks.git
        dest: /home/cloud_user/playbooks
