---
- hosts: playground
  become: yes
  become_method: sudo
  remote_user: cloud_user
  gather_facts: yes
  tasks:
    - name: update yum repos
      yum:
        name: '*'
        state: latest
    - name: install bash completion
      yum:
        name: bash-completion
        state: latest
    - name: install epel release
      yum:
        name: epel-release
        state: latest
        update_cache: yes
    - name: ensure apache2 is not installed
      yum:
        name: httpd
        state: absent
    - name: install nginx
      yum:
        name: nginx
        state: latest
      notify: 
        - service nginx start
    - name: enable nginx
      service:
        name: nginx
        enabled: yes
    - name: install nfs
      yum:
        name: nfs-utils
        state: latest
    - name: ensure nfs is up
      service:
        name: nfs
        state: started
        enabled: yes
    - name: install latest python3 package
      yum:
        name: python34
        state: latest
    - name: install git
      yum:
        name: git
        state: latest
    - name: install star archiving tool
      yum:
        name: star
        state: latest
    - name: install tree utility
      yum: 
        name: tree
        state: latest
    - name: change prompt
      lineinfile:
        path: /home/cloud_user/.bashrc
        line: 'export PS1="\[\033[38;5;202m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;221m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"' 
        backup: yes
  handlers:
    - name: service nginx start
      service:
        name: nginx
        state: started
