---
- hosts: playground
  become: yes
  become_method: sudo
  remote_user: cloud_user
  gather_facts: yes
  tasks:
    - name: update yum repos
      yum:
        name: '*'
        state: latest
    - name: install bash completion
      yum:
        name: bash-completion
        state: latest
    - name: install epel release
      yum:
        name: epel-release
        state: latest
        update_cache: yes
    - name: install various programming tools
      yum:
        name: ['ruby','nodejs','gcc','java','golang']
        state: present
