--- # Installing,configuring docker environment on rhel/centos systems
- hosts: playground
  become: yes
  become_method: sudo
  remote_user: cloud_user
  gather_facts: yes
  tasks:
    - name: update yum repos
      yum:
        name: '*'
        state: latest
    - name: install epel release
      yum:
        name: epel-release
        state: latest
        update_cache: yes
    - name: install dependencies
      yum:
        name: '{{ packages }}'
        state: latest
      vars:
        packages:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
    - name: add docker repo
      yum_repository:
        name: docker
        description: docker repo
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    - name: install docker
      yum:
        name: '{{ items }}'
        state: latest
        disable_gpg_check: yes
      vars:
        items: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: add user to docker group
      user:
        name: cloud_user
        groups: wheel,docker
