---
- hosts: vagrant
  become: yes
  become_method: sudo
  remote_user: vagrant
  gather_facts: yes
  tasks:
    - name: install latest python3 package
      apt:
        name: python3
        state: latest
    - name: install git
      apt:
        name: git
        state: latest
    - name: change prompt
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'export PS1="\[\033[38;5;202m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;221m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"' 
        backup: yes
