---
- hosts: playground
  become: yes
  become_method: sudo
  remote_user: cloud_user
  gather_facts: yes
  tasks:
    - name: update yum repos
      yum:
        name: '*'
        state: latest
    - name: install bash completion
      yum:
        name: bash-completion
        state: latest
    - name: install epel release
      yum:
        name: epel-release
        state: latest
        update_cache: yes
    - name: ensure nginx is not up
      service:
        name: nginx
        state: stopped
        enabled: no
    - name: install apache2
      yum:
        name: httpd
        state: latest
      notify:
        - service apache start
    - name: enable apache
      service:
        name: httpd
        enabled: yes
    - name: install nfs
      yum:
        name: nfs-utils
        state: latest
    - name: ensure nfs is up
      service:
        name: nfs
        state: started
        enabled: yes
    - name: install latest python3 package
      yum:
        name: python34
        state: latest
    - name: install git
      yum:
        name: git
        state: latest
    - name: install star archiving tool
      yum:
        name: star
        state: latest
    - name: install tree utility
      yum:
        name: tree
        state: latest
    - name: install certbot with yum-utils
      yum:
        name: ['yum-utils','certbot','python2-certbot-apache']
        state: latest
    - name: install docker
      yum:
        name: '{{ items }}'
        state: latest
        disable_gpg_check: yes
      vars:
        items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
#    - name: activate certbot
#      shell: "certbot --apache >/dev/null 2>&1"
    - name: cron certbot renewal
      cron:
        name: "certbot renew"
        minute: "0"
        hour: "15,20"
        job: "certbot renew >/dev/null 2>&1"
        user: root

    - name: change prompt
      lineinfile:
        path: /home/cloud_user/.bashrc
        line: 'export PS1="\[\033[38;5;202m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;221m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'
        backup: yes
  handlers:
    - name: service apache start
      service:
        name: httpd
        state: started
