---
- hosts: vagrant
  become: yes
  become_method: sudo
  remote_user: vagrant
  gather_facts: False
  pre_tasks:
    - name: raw install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
