---
- hosts: azure-instances
  tasks:
          - name: updating apt repositories
            apt:
              update_cache: yes  
            become: yes
          - name: upgrading packages
            apt:
              upgrade: yes
            become: yes
          - name: python is installing
            apt:
              name: python
              state: present
          - name: ensure pip is installed
            apt:
                    name: python-pip
                    state: latest
            become: yes
          - name: install nginx
            apt:
                    name: nginx
                    state: latest
            become: yes
          - name: start nginx
            service:
              name: nginx
              state: started
            become: yes
          - name: enable nginx
            service:
              name: nginx
              enabled: yes
            become: yes
          - name: install ntp
            apt:
              name: ntp
              state: present
            become: yes
            notify:
               
          - name: Start ntp service
            service: 
              name: ntp
              state: started
            become: yes
          - name: Enable service ntp
            service:
              name: ntp
              enabled: yes
            become: yes
          - name: Really useful stuff to install cowsay
            apt:
              name: cowsay
              state: latest
            become: yes
          - name: Update public ip text file
            shell: curl ifconfig.co > $HOME/public_ip.txt
          - name: Get private ip and save to text file
            shell: hostname -I | awk '{print $1}' > $HOME/private_ip.txt 
...            
